import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import Link from 'next/link'
import { getPages, getSiteColors, getSiteMainHeader } from '@/sanity/sanity-utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'My Awesome Site',
  description: 'Generated by Next + Sanity',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pages = await getPages();
  const siteColors = await getSiteColors();
  const headerColor = siteColors?.headerColor?.value;
  const bodyColor = siteColors?.backgroundColor?.value;
  const siteMainHeader = await getSiteMainHeader();
  const mainNavLinks = siteMainHeader.links

  const headerInlineStyle = {
    backgroundColor: headerColor,
  };

  const bodyInlineStyle = {
    backgroundColor: bodyColor,
  };


  return (
    <html lang="en" >
      <body className={`${inter.className} max-w-3xl mx-auto py-10`}>
        <header className='flex items-center justify-between p-5 rounded-md' style={headerInlineStyle}>
          <Link
            href="/"
            className='bg-gradient-to-r from-orange-400 via-red-500 to-purple-600 bg-clip-text 
          text-transparent text-lg font-bold'
          >
            David
          </Link>

          <div className='flex items-center gap-5 text-sm text-gray-600'>
            {mainNavLinks.map((link) => (
              <Link
              className='hover:text-gray-800 hover:underline'
                key={link.title}
                href={link.type === 'customLink' ? link.url : `/${link.url}`}
              >
                {link.title}
              </Link>
            ))}
          </div>
        </header>

        <main className='py-20 px-5 mt-8 rounded-md'  style={bodyInlineStyle}>{children}</main>
      </body>
    </html>
  )
}
